version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    env_file:
      - .env
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    networks:
      - front_back_mongo_network

  backend:
    container_name: goals_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - front_back_mongo_network
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    container_name: goals_frontend
    build: ./frontend
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend


volumes:
  mongo_data:
    name: mongo_data

networks:
  front_back_mongo_network:
    name: front_back_mongo_network
    driver: bridge